---
- hosts: all
  become: true
  pre_tasks:

  - name: Update(Ubuntu)
    apt:
      state: latest
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: server
  become: true
  roles:
    - Keystone
    - Glance
    - Nova
